import type { CleanupItem } from "@/lib/cleaner-store";
import type { RecommendationReason } from "./ai-types";

export function explainRecommendation(item: CleanupItem, reason: RecommendationReason): string {
  if (reason === "protected") return "This item is protected and excluded from cleanup.";
  if (reason === "exact-duplicate") return "Matching signatures suggest this is an exact duplicate; one copy is kept protected.";
  if (reason === "near-duplicate") return "The filename pattern indicates a duplicate variant. Review before removing.";
  if (reason === "representative") return "This looks like the representative copy for its duplicate group and is kept.";
  if (reason === "large-file") return "Large files can reclaim significant space, but should be reviewed before removal.";
  if (reason === "temporary") return "Temporary data is generally safe to remove and can be regenerated by apps.";
  if (reason === "old-item") return "This item appears older and less likely to be actively needed.";
  return "Confidence is lower for this item, so manual review is recommended.";
}
